version: '3.4'

services:
  moneytracker:
    image: ${DOCKER_REGISTRY-}moneytracker
    build:
      context: .
      dockerfile: MoneyTracker/Dockerfile
    ports:
    - "8080:8080"
    - "8081:8081"

  moneytracker.database:
    image: postgres:latest
    container_name: moneytracker.database
    environment:
        - POSTGRES_DB=moneytrackertz
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123 
    volumes:
        -  ./.containers/moneytracker-db:/var/lib/postgresql/data
    ports:
        - 5432:5432